import { OrgInvite, Organization, Project, SecurityGroup, Task, Team, User as UserType } from '../../types';
import { UserSettings } from '../../services/settingsService';
import { SettingsTabType } from '../SettingsModal';

export interface SettingsModalContentProps {
  activeTab: SettingsTabType;
  canAccessWorkflowAutomation: boolean;
  canManageWorkflowAutomation: boolean;
  user: UserType;
  profileUser: UserType | null;
  org: Organization | null;
  allUsers: UserType[];
  groups: SecurityGroup[];
  teams: Team[];
  settings: UserSettings;
  setTeams: (teams: Team[]) => void;
  setGroups: (groups: SecurityGroup[]) => void;
  projects: Project[];
  workflowProjects: Project[];
  projectTasks: Task[];
  projectQuery: string;
  setProjectQuery: (value: string) => void;
  activeProjects: Project[];
  archivedProjects: Project[];
  completedProjects: Project[];
  deletedProjects: Project[];
  focusedProjectId: string | null;
  setFocusedProjectId: (id: string | null) => void;
  focusedProject: Project | null;
  focusedProjectTasks: Task[];
  editingProjectId: string | null;
  editingProjectName: string;
  setEditingProjectId: (id: string | null) => void;
  setEditingProjectName: (value: string) => void;
  submitProjectRename: () => void;
  onCompleteProject?: (id: string) => void;
  onReopenProject?: (id: string) => void;
  onArchiveProject?: (id: string) => void;
  onRestoreProject?: (id: string) => void;
  onDeleteProject?: (id: string) => void;
  onPurgeProject?: (id: string) => void;
  onUpdateProject?: (id: string, updates: Partial<Project>) => void;
  onChangeProjectOwner?: (id: string, ownerId: string) => void;
  onDeleteOrganization: () => Promise<void>;
  onToggle: (key: keyof UserSettings) => void;
  onThemeChange: (theme: UserSettings['theme']) => void;
  onUpdateSettings: (updates: Partial<UserSettings>) => void;
  onThresholdChange: (value: number) => void;
  onAvatarUpdate: (avatar: string) => Promise<void>;
  onChangePassword: (currentPassword: string, newPassword: string, confirmPassword: string) => Promise<{ success: boolean; error?: string }>;
  onUpdateProfileName: (firstName: string, lastName: string) => Promise<{ success: boolean; error?: string }>;
  isProvisioning: boolean;
  setIsProvisioning: (value: boolean) => void;
  newUserName: string;
  setNewUserName: (value: string) => void;
  newUserFirstName: string;
  setNewUserFirstName: (value: string) => void;
  newUserLastName: string;
  setNewUserLastName: (value: string) => void;
  newUserEmail: string;
  setNewUserEmail: (value: string) => void;
  newUserRole: 'member' | 'admin';
  setNewUserRole: (value: 'member' | 'admin') => void;
  newUserTempPassword: string;
  setNewUserTempPassword: (value: string) => void;
  provisionError: string;
  handleProvision: (e: React.FormEvent) => Promise<void>;
  seatPurchaseCount: number;
  setSeatPurchaseCount: (value: number) => void;
  handleBuyMoreSeats: () => Promise<void>;
  editingUserId: string | null;
  editFirstNameValue: string;
  setEditFirstNameValue: (value: string) => void;
  editLastNameValue: string;
  setEditLastNameValue: (value: string) => void;
  editEmailValue: string;
  setEditEmailValue: (value: string) => void;
  handleCommitEdit: () => Promise<void>;
  handleStartEdit: (targetUser: UserType) => void;
  handleUpdateUserRole: (userId: string, role: 'admin' | 'member') => Promise<void>;
  handlePurgeUser: (userId: string) => Promise<void>;
  invites: OrgInvite[];
  newInviteIdentifier: string;
  setNewInviteIdentifier: (value: string) => void;
  newInviteRole: 'member' | 'admin';
  setNewInviteRole: (value: 'member' | 'admin') => void;
  handleCreateInvite: () => Promise<void>;
  handleRevokeInvite: (inviteId: string) => Promise<void>;
  handleResendInvite: (inviteId: string) => Promise<void>;
  refreshWorkspaceUsers: () => Promise<void>;
  aiUsageRows: Array<{
    id: string;
    orgId: string;
    dayKey: string;
    requestsUsed: number;
    tokensUsed: number;
    warningIssuedAt?: string | null;
    blockedAt?: string | null;
  }>;
  refreshAiUsage: () => Promise<void>;
  onUpdateOrganizationSettings: (patch: Partial<Pick<Organization, 'loginSubdomain' | 'allowMicrosoftAuth' | 'microsoftWorkspaceConnected'>>) => Promise<void>;
}
